spring.application.name=radar
# Configuración de PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/radar_bd}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SERVER
# =========================

server.servlet.context-path=/api/v1
server.port=${PORT:8080}

# =========================
# JWT
# =========================

application.jwt.secret-key=supersecretkeythatshouldbelongandcomplexsupersecretkeythatshouldbelongandcomplex
application.jwt.token-prefix=Bearer
application.jwt.token-expiration-after-days=7
application.jwt.refresh-token-expiration-after-days=30

# Ocultar stacktrace en las respuestas de error pero mostrar el mensaje de validación
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always

# Evitar que Spring Boot DevTools sobrescriba las propiedades de error en desarrollo
spring.devtools.add-properties=false